#ifndef  DEVICEMAPMARCO_H
#define DEVICEMAPMARCO_H

/************************************************************/
/* PCI、PCIE 设备操作API宏映射 ,用于IO控制                 */
/************************************************************/
#include<windows.h>
struct MemWrtReg
{
    ULONG BARADD;
    ULONG OFFSET;
    ULONG DATA;
};
struct MemReadReg
{
    ULONG  BARADD;
    ULONG  OFFSET;
};

#define PCIEDRIVER_IOCTL_WRITEREG      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PCIEDRIVER_IOCTL_READREG       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PCIEDRIVER_IOCTL_MAPADDR       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PCIEDRIVER_IOCTL_UNMAPADDR     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PCIEDRIVER_IOCTL_MAPEVT        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PCIEDRIVER_IOCTL_SETADDR       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FPGAISP       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#endif
